### PR TITLE
Addition of echosounder detector remora 

### PR DESCRIPTION
**Pull request by MZiegenhorn**
This branch was created by MAZ in late 2020 to include the recently coded echosounder detector as a Triton Remora. This detector was based on the explosion detector and functions primarily by comparing the normalized waveform envelope of a template echosounder signal to the normalized waveform envelope of various input signals. Settings that can be tweaked to improve performance include the similarity of the signal to the template (i.e. correlation thresholds) and the timing between signals (i.e. IPI thresholds). 

This branch contains the following items: 

1. Basic initialization codes for the remora (i.e. initialize.mat, ec_pulldown.mat ...)

2. Functions/scripts related to the main functionality (i.e. running the detector)

3. Base settings files / base echosounder template

4. **Functions/scripts related to post-processing.** These include code that allows the user to turn a folder of detector output files into an ID file, which can then be used in LabelVis to visualize detector output. Creation of said ID file is an option in the remora's pulldown menu. Additionally, a script entitled 'ec_mkTPWS' is included which does _not_ have an associated GUI but converts a disk of echosounder output into a TPWS format that can then be loaded into detEdit for perusal and removal of false detections. 

Please let me know if you have any questions/changes you believe need to be made before this is merged into the master version of Triton.

### CODE REVIEW

**Comment by fascimare** [comment]
Hi Morgan,
I've looked through the branch and the only comment I have is for Line 135 in echosounder_detector.m: In the comment above you mention that you add 100 points to make sure you get the whole detection time series, but in the line you add 600 points. Is that correct and is the comment wrong, or the other way around?

**Comment by MZiegenhorn** [comment]
Hey Annebelle, 

The comment is wrong in that case. I forgot to modify the comment when I changed from 100 to 600 points.

**Comment by fascimare** [comment]
Ok, then this branch is good to go.

**Comment by kfrasier** [comment]
Merged! Please delete branch when you're ready.

**Pull request merged**
