### PR TITLE
Label remora

### PR DESCRIPTION
**Pull request by MZiegenhorn**
I think the labelling remora is ready for review so that it can be added into Triton and everyone can use it!

### CODE REVIEW

**Comment by kfrasier** [comment]
Awesome! This looks really close!

A couple of things just from scanning through quickly:

- As much as "LabelLord" makes me  😁 I'm not sure it's sets quite the tone we're going for with Triton as a whole? What about something slightly more boring, like TritonLabels or LabelEditor? Sorry, it's not you, it's the world that takes itself too seriously perhaps...  😟 

- Can you remove the .zip and config files from your commit? And maybe also plot_chLab_wav.m, which looks empty?

- There's one file in your commit that is actually in the ship detector remora - are you sure you want to modify that one? I'm not up to speed on what you and Alba have worked on, maybe that's intentional?

- There are a few cases where the function name inside the .m file doesn't match the file name, can you scan through and double check for those? The most important one to fix is ioWriteLabel, since I imagine there might be other functions named that inside the repository, so could get weird conflicts. sh_create_tlab_file also. Not sure if there are others.

Other than that I think it looks really good! Love your file structure and naming conventions, and the code looks so clean!! 👍 👍 👍  
A bunch of people are excited to start using this, great work!

**Comment by MZiegenhorn** [comment]
reply to Kait: 

-removed things you pointed out, and fixed functions so that the file names match what's inside. I can't believe I had so many of those that were off!!!

-yes, there are a few things taken straight from the ship detector; Alba told me to just take the making tLabs from different file types (besides detEdit files) from her code and add it into this remora as well. 

-figured Label Lord wouldn't fly; I had a backup name :p

**Comment by asolsonaberga** [comment]
@MZiegenhorn, the files from the ship detector I would copy but rename them in your remora.

**Comment by MZiegenhorn** [comment]
@asolsonaberga  I gave them different prefixes, but I could make the names more distinct if you think it's needed?

**Comment by asolsonaberga** [comment]
Great. Just make sure that it works for .cTg files and other files with the spectrogram and timeseries. IT worked well for the LTSAs in the ship detector, so I don't know if you have tested it for the others.
If it works great, then good to go.

**Comment by MZiegenhorn** [comment]
I haven't tested the make tlabs from a text file, but once those are made I don't think there's any reason why they would display differently from other tlabs. I don't happen to have any text files on hand to test with.

**Comment by kfrasier** [comment]
In this file: Remoras/Ship-Detector/gui/sh_create_tlab_file.m the function is internally renamed to lt_create_tlab_file, but the file being modified lives in the ship detector code. 

I think you want to save the version of that file under the name lt_create_tlab_file, in the label remora folder. Otherwise this will overwrite the ship detector version. Right?

**Comment by MZiegenhorn** [comment]
@kfrasier definitely. Not sure how that happened, let me look

**Comment by MZiegenhorn** [comment]
pushed change should fix that issue

**Pull request merged**
